### ISSUE TITLE
Change highlighted menu item via function

### ISSUE THREAD

**Issue by edcousins** [pixyzehn/MediumMenu#1]
Hey there!

Thanks for sharing this. Just wondering if there if you have any function that can update the highlighted menu item from another viewcontroller - for example if you navigate to a viewcontroller via the menu, and then return via a segue, the menu will now show the wrong highlighted item.

If not, I'll try and write something up.

Thanks in advance.

**Comment by pixyzehn** [comment]
@edcousins 
Hi, Thank you for your comment. I'll check that bug and If there are some bugs, I'll try to fix that.

**Comment by pixyzehn** [comment]
@edcousins 
Hi, sorry for late. I added some functions that can update the highlighted menu item from another viewcontroller.This version is 1.0.4.

**Comment by edcousins** [comment]
Wow thanks a lot, wasn't expecting it that quick! :)

**Comment by pixyzehn** [comment]
@edcousins
You're welcome :)
