### ISSUE TITLE
XCode 7.1 Beta

### ISSUE THREAD

**Issue by buturab** [pixyzehn/MediumMenu#10]
MediumMenu package does not compile on XCode 7.1. There is a wrapping issue that needs to be fixed after which it functions properly.

**Comment by zeroskill** [comment]
These issues are easily fixable via the builtin Swift 2 code updater. Just need the project owner to apply them and push them.

**Comment by pixyzehn** [comment]
Thanks for letting me know. I will update soon.

**Comment by pixyzehn** [comment]
Fixed.
