### ISSUE TITLE
Push/ShowViewController breaks application

### ISSUE THREAD

**Issue by AttilaTheFun** [pixyzehn/MediumMenu#2]
Hello! I really like your Medium Menu. I'm an iOS developer at Yelp and would love to use it in one of my personal projects. Unfortunately, currently pushing new view controllers onto the navigation controller's stack breaks everything currently. Any chance we could fix this?

![screen shot 2015-04-08 at 12 37 46 am](https://cloud.githubusercontent.com/assets/3255391/7040788/82f15298-dd87-11e4-9a98-b7af19511e5a.png)

**Comment by pixyzehn** [comment]
Hi, Thank you for your comment. I'll reproduce the bug, and then fix that as soon as possible. After modification, I'll mention it.

**Comment by pixyzehn** [comment]
@AttilaTheFun 
Hi, I didn't reproduce that bug. If possible, tell me about the details. And I'd like to know the difference between your project code and MediumMenu sample code.

**Comment by rodrynet** [comment]
Need your help! please! If i use a view for login and then your proyect, how can i dismiss the view of the mediumMenu? thankyou

**Comment by pixyzehn** [comment]
@rodrynet 
I'm sorry for the late response. First, Thank you for using my project. Please let me know more details.
