### ISSUE TITLE
Landscape mode not filled with color

### ISSUE THREAD

**Issue by VeveCorp** [pixyzehn/MediumMenu#20]
White Background
https://gyazo.com/2369a4adc84390dc33198f2893f4b161

Black Background
https://gyazo.com/528e2317cadc7650c5fd191f614b467c

What I noticed while testing this framework was that, if the app was ever in landscape mode the tableview would show the black background, so I went to original  and saw the same issue in the demo project also; in terms of the two backgrounds not blending together, do you know of a fix for it?

    override public init(frame: CGRect) {
        super.init(frame: frame)
        self.titleFont           = UIFont(name: "HelveticaNeue-Light", size: 28)
        self.titleAlignment      = .Left
        self.height              = 400 // updated to good-fit height for iPhone 4s
        self.textColor           = Color.mediumBlackColor
        self.highlightTextColor  = Color.mediumGlayColor
        self.menuBackgroundColor = Color.mediumWhiteColor
        self.bounceOffset        = 0
        self.velocityTreshold    = 1000
        self.panGestureEnable    = true
        self.highlighedIndex     = 1
    }

**Comment by VeveCorp** [comment]
Fixed it by adding to the UIViewController the color also.

https://gyazo.com/25384ad8b1c67ed13a821c894a57adbb

       let menuController = UIViewController()
        menuController.view = self
        menuController.view.backgroundColor = Color.mediumWhiteColor
        UIApplication.sharedApplication().delegate?.window??.rootViewController = menuController
        UIApplication.sharedApplication().delegate?.window??.addSubview(contentController!.view)

**Comment by trusk89** [comment]
@VeveCorp  This still reproduces on latest version from Cocoapods

![img_3964](https://cloud.githubusercontent.com/assets/6096120/22018437/8576d52a-dcb7-11e6-85b6-9d1f31ca70ea.PNG)
