### ISSUE TITLE
Not working in landscape mode

### ISSUE THREAD

**Issue by justinthiele** [pixyzehn/MediumMenu#3]
First of all, thanks for creating MediumMenu! I really like the look and functionality. 

I have the menu working well in portrait mode, but when I turn the phone to landscape, the application no longer expands to fill the screen.

Any tips on getting this to work in landscape?

Thanks!

**Comment by pixyzehn** [comment]
@justinthiele
Sorry for the delay. I'll check the bug in landscape mode. And then if it is possible, I'll modify that.

**Comment by justinthiele** [comment]
Thanks! Let me know if you need help reproducing the bug.

**Comment by pixyzehn** [comment]
@justinthiele
Sure. Thank you for telling me. Please wait for a while.

**Comment by pixyzehn** [comment]
@justinthiele 
Hi, sorry for late. I fixed this issue on version 1.0.5. But you need to adjust a parameter. 
Please feel free to ask anything If you have any questions :)

**Comment by justinthiele** [comment]
For some reason the menu's background color isn't getting set. It just shows as white now instead of dark gray. 

Landscape mode works now though!

Thanks!

**Comment by pixyzehn** [comment]
@justinthiele 
> For some reason the menu's background color isn't getting set. It just shows as white now instead of dark gray.
Sure. I'll check and fix this problem.

You're welcome :+1:

**Comment by pixyzehn** [comment]
@justinthiele 
I modified the problem about  background color. Please check it after updating version 1.0.6.

**Comment by justinthiele** [comment]
This is working great now, thank you!
