### ISSUE TITLE
Presenting UIViewController

### ISSUE THREAD

**Issue by martisan** [pixyzehn/MediumMenu#5]
When trying to present a UIViewController from the HomeViewController in the example I get the following error: "Presenting view controllers on detached view controllers is discouraged."

How are you presenting modal view controllers?

**Comment by pixyzehn** [comment]
Sorry for late..
Oh, really?
I cannot reproduce this error.
What your Xcode and MediumMenu version?

**Comment by martisan** [comment]
Not a problem at all. Thanks for the response.
Xcode 6.3.2 and MediumMenu 1.0.6

I've got a view controller with a storyboard id of "Login"
So I try to instantiate it with storyboard id and present it in HomeViewController from example.

**Comment by pixyzehn** [comment]
@martisan 
Thanks much!
That's good to hear.
