### ISSUE TITLE
User interaction enabled on main view

### ISSUE THREAD

**Issue by ds1239** [pixyzehn/MediumMenu#6]
Hello. Whenever I tap on the main view (the one that slides down when the menu comes out), it messes up the constraints on that view. Is there a way to fix this, or have user interaction be disabled on that view when the menu is out?

**Comment by pixyzehn** [comment]
Hi, @ds1239 
Let me know more details. I will fix that bug.

**Comment by ds1239** [comment]
So I tap on a table view cell on the main view when the menu is out, it segues to another view and the constraints are messed up.

**Comment by ds1239** [comment]
Everything is moved up.

**Comment by pixyzehn** [comment]
@ds1239 
How do you use segues to another view and the constraints? By writing code or using storyboard?

**Comment by ds1239** [comment]
All through storyboard.

Dani Smith
(248) 229-9912
danismith271@gmail.com

**Comment by ds1239** [comment]
Do you know of any quick fixes I could implement to simply disable user interaction on that view while the menu is out? I appreciate all of the help.

**Comment by pixyzehn** [comment]
@ds1239 
Sorry, I have no idea now. But In my sample project, constraints are correct.
