### ISSUE TITLE
Documentation for How to Show Status Bar?

### ISSUE THREAD

**Issue by davecom** [pixyzehn/MediumMenu#7]
Documentation explains how to get rid of it, but it doesn't explain how to have it shown.  I am seeing it covered by all black when incorporating MediumMenu.

**Comment by pixyzehn** [comment]
Hi @davecom,
I think it shows by default setting. But now you cannot see it because MediumMenu background color is black, right?
You need to change MediumMenu background color or change text color in status bar when showing MediumMenu.
If you are in trouble, let me know.
